/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChapterId = IDL.Text;
export const UploadStatus = IDL.Variant({
  'published' : IDL.Null,
  'uploading' : IDL.Null,
  'draft' : IDL.Null,
  'failed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UploadSession = IDL.Record({
  'status' : UploadStatus,
  'updated_at' : Timestamp,
  'chapter_id' : ChapterId,
  'uploaded_blobs' : IDL.Vec(ExternalBlob),
  'started_at' : Timestamp,
});
export const ComicId = IDL.Text;
export const ChapterView = IDL.Record({
  'id' : ChapterId,
  'title' : IDL.Text,
  'updated_at' : Timestamp,
  'created_at' : Timestamp,
  'comic_id' : ComicId,
  'is_published' : IDL.Bool,
  'number' : IDL.Float64,
  'image_blobs' : IDL.Vec(ExternalBlob),
});
export const CreateChapterArgs = IDL.Record({
  'title' : IDL.Text,
  'comic_id' : ComicId,
  'number' : IDL.Float64,
});
export const CreateComicArgs = IDL.Record({
  'title' : IDL.Text,
  'cover_blob' : ExternalBlob,
  'description' : IDL.Text,
});
export const UserId = IDL.Principal;
export const ComicView = IDL.Record({
  'id' : ComicId,
  'title' : IDL.Text,
  'updated_at' : Timestamp,
  'cover_blob' : ExternalBlob,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'author_id' : UserId,
});
export const ProfileId = IDL.Text;
export const ReadProgress = IDL.Record({
  'user_id' : ProfileId,
  'comic_id' : ComicId,
  'scroll_pixel_y' : IDL.Nat,
  'chapter_id' : ChapterId,
  'last_read_at' : Timestamp,
});
export const Comic = IDL.Record({
  'id' : ComicId,
  'title' : IDL.Text,
  'updated_at' : Timestamp,
  'cover_blob' : ExternalBlob,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'author_id' : UserId,
  'is_deleted' : IDL.Bool,
});
export const TrendingEntry = IDL.Record({
  'views' : IDL.Nat,
  'last_updated' : Timestamp,
  'comic_id' : ComicId,
  'hot_score' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'id' : ProfileId,
  'bio' : IDL.Text,
  'updated_at' : Timestamp,
  'created_at' : Timestamp,
  'profile_picture_url' : IDL.Opt(IDL.Text),
  'display_name' : IDL.Text,
  'auth_id' : IDL.Text,
  'handle' : IDL.Text,
  'is_creator' : IDL.Bool,
});
export const SaveReadProgressRequest = IDL.Record({
  'comic_id' : ComicId,
  'scroll_pixel_y' : IDL.Nat,
  'chapter_id' : ChapterId,
});
export const UpdateChapterDraftArgs = IDL.Record({
  'title' : IDL.Text,
  'number' : IDL.Float64,
});
export const UpdateComicArgs = IDL.Record({
  'title' : IDL.Text,
  'cover_blob' : ExternalBlob,
  'description' : IDL.Text,
});
export const UpdateProfileRequest = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'profile_picture_url' : IDL.Opt(IDL.Text),
  'display_name' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'beginUpload' : IDL.Func([ChapterId], [UploadSession], []),
  'commitUpload' : IDL.Func([ChapterId], [ChapterView], []),
  'createChapter' : IDL.Func([CreateChapterArgs], [ChapterView], []),
  'createComic' : IDL.Func([CreateComicArgs], [ComicView], []),
  'deleteChapter' : IDL.Func([ChapterId], [], []),
  'deleteComic' : IDL.Func([ComicId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([ChapterId], [IDL.Opt(ChapterView)], ['query']),
  'getComic' : IDL.Func([ComicId], [IDL.Opt(ComicView)], ['query']),
  'getMyReadProgress' : IDL.Func([ComicId], [IDL.Opt(ReadProgress)], ['query']),
  'getMyResumeReading' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(Comic, ReadProgress))],
      ['query'],
    ),
  'getTrendingComics' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TrendingEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'incrementComicViews' : IDL.Func([ComicId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChapters' : IDL.Func([ComicId], [IDL.Vec(ChapterView)], ['query']),
  'listComics' : IDL.Func([], [IDL.Vec(ComicView)], ['query']),
  'registerUploadedImage' : IDL.Func(
      [ChapterId, ExternalBlob],
      [UploadSession],
      [],
    ),
  'rollbackUpload' : IDL.Func([ChapterId], [IDL.Nat], []),
  'saveMyReadProgress' : IDL.Func([SaveReadProgressRequest], [], []),
  'updateChapterDraft' : IDL.Func(
      [ChapterId, UpdateChapterDraftArgs],
      [ChapterView],
      [],
    ),
  'updateComic' : IDL.Func([ComicId, UpdateComicArgs], [ComicView], []),
  'updateMyProfile' : IDL.Func([UpdateProfileRequest], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChapterId = IDL.Text;
  const UploadStatus = IDL.Variant({
    'published' : IDL.Null,
    'uploading' : IDL.Null,
    'draft' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UploadSession = IDL.Record({
    'status' : UploadStatus,
    'updated_at' : Timestamp,
    'chapter_id' : ChapterId,
    'uploaded_blobs' : IDL.Vec(ExternalBlob),
    'started_at' : Timestamp,
  });
  const ComicId = IDL.Text;
  const ChapterView = IDL.Record({
    'id' : ChapterId,
    'title' : IDL.Text,
    'updated_at' : Timestamp,
    'created_at' : Timestamp,
    'comic_id' : ComicId,
    'is_published' : IDL.Bool,
    'number' : IDL.Float64,
    'image_blobs' : IDL.Vec(ExternalBlob),
  });
  const CreateChapterArgs = IDL.Record({
    'title' : IDL.Text,
    'comic_id' : ComicId,
    'number' : IDL.Float64,
  });
  const CreateComicArgs = IDL.Record({
    'title' : IDL.Text,
    'cover_blob' : ExternalBlob,
    'description' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const ComicView = IDL.Record({
    'id' : ComicId,
    'title' : IDL.Text,
    'updated_at' : Timestamp,
    'cover_blob' : ExternalBlob,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'author_id' : UserId,
  });
  const ProfileId = IDL.Text;
  const ReadProgress = IDL.Record({
    'user_id' : ProfileId,
    'comic_id' : ComicId,
    'scroll_pixel_y' : IDL.Nat,
    'chapter_id' : ChapterId,
    'last_read_at' : Timestamp,
  });
  const Comic = IDL.Record({
    'id' : ComicId,
    'title' : IDL.Text,
    'updated_at' : Timestamp,
    'cover_blob' : ExternalBlob,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'author_id' : UserId,
    'is_deleted' : IDL.Bool,
  });
  const TrendingEntry = IDL.Record({
    'views' : IDL.Nat,
    'last_updated' : Timestamp,
    'comic_id' : ComicId,
    'hot_score' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'id' : ProfileId,
    'bio' : IDL.Text,
    'updated_at' : Timestamp,
    'created_at' : Timestamp,
    'profile_picture_url' : IDL.Opt(IDL.Text),
    'display_name' : IDL.Text,
    'auth_id' : IDL.Text,
    'handle' : IDL.Text,
    'is_creator' : IDL.Bool,
  });
  const SaveReadProgressRequest = IDL.Record({
    'comic_id' : ComicId,
    'scroll_pixel_y' : IDL.Nat,
    'chapter_id' : ChapterId,
  });
  const UpdateChapterDraftArgs = IDL.Record({
    'title' : IDL.Text,
    'number' : IDL.Float64,
  });
  const UpdateComicArgs = IDL.Record({
    'title' : IDL.Text,
    'cover_blob' : ExternalBlob,
    'description' : IDL.Text,
  });
  const UpdateProfileRequest = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'profile_picture_url' : IDL.Opt(IDL.Text),
    'display_name' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'beginUpload' : IDL.Func([ChapterId], [UploadSession], []),
    'commitUpload' : IDL.Func([ChapterId], [ChapterView], []),
    'createChapter' : IDL.Func([CreateChapterArgs], [ChapterView], []),
    'createComic' : IDL.Func([CreateComicArgs], [ComicView], []),
    'deleteChapter' : IDL.Func([ChapterId], [], []),
    'deleteComic' : IDL.Func([ComicId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([ChapterId], [IDL.Opt(ChapterView)], ['query']),
    'getComic' : IDL.Func([ComicId], [IDL.Opt(ComicView)], ['query']),
    'getMyReadProgress' : IDL.Func(
        [ComicId],
        [IDL.Opt(ReadProgress)],
        ['query'],
      ),
    'getMyResumeReading' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(Comic, ReadProgress))],
        ['query'],
      ),
    'getTrendingComics' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TrendingEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'incrementComicViews' : IDL.Func([ComicId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChapters' : IDL.Func([ComicId], [IDL.Vec(ChapterView)], ['query']),
    'listComics' : IDL.Func([], [IDL.Vec(ComicView)], ['query']),
    'registerUploadedImage' : IDL.Func(
        [ChapterId, ExternalBlob],
        [UploadSession],
        [],
      ),
    'rollbackUpload' : IDL.Func([ChapterId], [IDL.Nat], []),
    'saveMyReadProgress' : IDL.Func([SaveReadProgressRequest], [], []),
    'updateChapterDraft' : IDL.Func(
        [ChapterId, UpdateChapterDraftArgs],
        [ChapterView],
        [],
      ),
    'updateComic' : IDL.Func([ComicId, UpdateComicArgs], [ComicView], []),
    'updateMyProfile' : IDL.Func([UpdateProfileRequest], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };