/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChapterId = bigint;
export interface ChapterInput {
  'title' : string,
  'chapterNumber' : bigint,
  'comicId' : ComicId,
  'images' : Array<string>,
}
export interface ChapterPublic {
  'id' : ChapterId,
  'title' : string,
  'chapterNumber' : bigint,
  'createdAt' : Timestamp,
  'comicId' : ComicId,
  'updatedAt' : Timestamp,
  'images' : Array<string>,
}
export type ComicId = bigint;
export interface ComicInput {
  'title' : string,
  'isPremium' : boolean,
  'description' : string,
  'author' : string,
  'ownerUploaded' : boolean,
  'isFeatured' : boolean,
  'genres' : Array<string>,
  'coverUrl' : string,
  'isPinned' : boolean,
  'isTrending' : boolean,
}
export interface ComicPublic {
  'id' : ComicId,
  'title' : string,
  'isPremium' : boolean,
  'createdAt' : Timestamp,
  'description' : string,
  'author' : string,
  'ownerUploaded' : boolean,
  'isFeatured' : boolean,
  'genres' : Array<string>,
  'coverUrl' : string,
  'likesCount' : bigint,
  'isPinned' : boolean,
  'isTrending' : boolean,
  'viewsCount' : bigint,
}
export interface Comment {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'chapterId' : [] | [ChapterId],
  'comicId' : ComicId,
}
export interface FAQInput {
  'question' : string,
  'answer' : string,
  'category' : string,
  'isUserQuestion' : boolean,
}
export interface FAQPublic {
  'id' : bigint,
  'upvotes' : bigint,
  'question' : string,
  'createdAt' : bigint,
  'answer' : string,
  'approved' : boolean,
  'category' : string,
  'isUserQuestion' : boolean,
}
export interface ReadingProgress {
  'scrollPosition' : bigint,
  'chapterId' : ChapterId,
  'comicId' : ComicId,
  'lastReadAt' : Timestamp,
}
export type Timestamp = bigint;
export type UserId = string;
export interface _SERVICE {
  'addComment' : ActorMethod<
    [UserId, ComicId, [] | [ChapterId], string],
    bigint
  >,
  'approveFAQ' : ActorMethod<[bigint], boolean>,
  'bookmarkComic' : ActorMethod<[ComicId], boolean>,
  'createChapter' : ActorMethod<[ChapterInput], ChapterId>,
  'createComic' : ActorMethod<[ComicInput], ComicId>,
  'createFAQ' : ActorMethod<[FAQInput], bigint>,
  'deleteChapter' : ActorMethod<[ChapterId], boolean>,
  'deleteComic' : ActorMethod<[ComicId], boolean>,
  'deleteFAQ' : ActorMethod<[bigint], boolean>,
  'getChapter' : ActorMethod<[ChapterId], [] | [ChapterPublic]>,
  'getComic' : ActorMethod<[ComicId], [] | [ComicPublic]>,
  'getLikes' : ActorMethod<[ComicId], [] | [bigint]>,
  'getProgress' : ActorMethod<[UserId, ComicId], [] | [ReadingProgress]>,
  'getTrending' : ActorMethod<[bigint], Array<ComicPublic>>,
  'getViews' : ActorMethod<[ComicId], [] | [bigint]>,
  'likeComic' : ActorMethod<[ComicId], boolean>,
  'listChapters' : ActorMethod<[ComicId], Array<ChapterPublic>>,
  'listComics' : ActorMethod<[], Array<ComicPublic>>,
  'listComments' : ActorMethod<[ComicId], Array<Comment>>,
  'listFAQs' : ActorMethod<[boolean], Array<FAQPublic>>,
  'listProgress' : ActorMethod<[UserId], Array<ReadingProgress>>,
  'saveProgress' : ActorMethod<[UserId, ReadingProgress], undefined>,
  'submitFAQ' : ActorMethod<[FAQInput], bigint>,
  'unbookmarkComic' : ActorMethod<[ComicId], boolean>,
  'unlikeComic' : ActorMethod<[ComicId], boolean>,
  'updateChapter' : ActorMethod<[ChapterId, ChapterInput], boolean>,
  'updateComic' : ActorMethod<[ComicId, ComicInput], boolean>,
  'updateFAQ' : ActorMethod<[bigint, FAQInput], boolean>,
  'viewComic' : ActorMethod<[ComicId], boolean>,
  'voteFAQ' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];