/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChapterId = string;
export interface ChapterView {
  'id' : ChapterId,
  'title' : string,
  'updated_at' : Timestamp,
  'created_at' : Timestamp,
  'comic_id' : ComicId,
  'is_published' : boolean,
  'number' : number,
  'image_blobs' : Array<ExternalBlob>,
}
export interface Comic {
  'id' : ComicId,
  'title' : string,
  'updated_at' : Timestamp,
  'cover_blob' : ExternalBlob,
  'genre_ids' : Array<string>,
  'description' : string,
  'created_at' : Timestamp,
  'author_id' : UserId,
  'is_deleted' : boolean,
}
export type ComicId = string;
export interface ComicView {
  'id' : ComicId,
  'title' : string,
  'updated_at' : Timestamp,
  'cover_blob' : ExternalBlob,
  'genre_ids' : Array<string>,
  'description' : string,
  'created_at' : Timestamp,
  'author_id' : UserId,
}
export interface CreateChapterArgs {
  'title' : string,
  'comic_id' : ComicId,
  'number' : number,
}
export interface CreateComicArgs {
  'title' : string,
  'cover_blob' : ExternalBlob,
  'genre_ids' : Array<string>,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export interface Genre { 'id' : GenreId, 'name' : string, 'slug' : string }
export type GenreId = string;
export type ProfileId = string;
export interface ReadProgress {
  'user_id' : ProfileId,
  'comic_id' : ComicId,
  'scroll_pixel_y' : bigint,
  'chapter_id' : ChapterId,
  'last_read_at' : Timestamp,
}
export interface SaveReadProgressRequest {
  'comic_id' : ComicId,
  'scroll_pixel_y' : bigint,
  'chapter_id' : ChapterId,
}
export type Timestamp = bigint;
export interface TrendingEntry {
  'views' : bigint,
  'last_updated' : Timestamp,
  'comic_id' : ComicId,
  'hot_score' : number,
}
export interface UpdateChapterDraftArgs { 'title' : string, 'number' : number }
export interface UpdateComicArgs {
  'title' : string,
  'cover_blob' : ExternalBlob,
  'genre_ids' : Array<string>,
  'description' : string,
}
export interface UpdateProfileRequest {
  'bio' : [] | [string],
  'profile_picture_url' : [] | [string],
  'display_name' : [] | [string],
}
export interface UploadSession {
  'status' : UploadStatus,
  'updated_at' : Timestamp,
  'chapter_id' : ChapterId,
  'uploaded_blobs' : Array<ExternalBlob>,
  'started_at' : Timestamp,
}
export type UploadStatus = { 'published' : null } |
  { 'uploading' : null } |
  { 'draft' : null } |
  { 'failed' : null };
export type UserId = Principal;
export interface UserProfile {
  'id' : ProfileId,
  'bio' : string,
  'updated_at' : Timestamp,
  'created_at' : Timestamp,
  'profile_picture_url' : [] | [string],
  'display_name' : string,
  'auth_id' : string,
  'handle' : string,
  'is_creator' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'beginUpload' : ActorMethod<[ChapterId], UploadSession>,
  'commitUpload' : ActorMethod<[ChapterId], ChapterView>,
  'createChapter' : ActorMethod<[CreateChapterArgs], ChapterView>,
  'createComic' : ActorMethod<[CreateComicArgs], ComicView>,
  'deleteChapter' : ActorMethod<[ChapterId], undefined>,
  'deleteComic' : ActorMethod<[ComicId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapter' : ActorMethod<[ChapterId], [] | [ChapterView]>,
  'getComic' : ActorMethod<[ComicId], [] | [ComicView]>,
  'getComicsByGenre' : ActorMethod<[GenreId], Array<ComicView>>,
  'getGenre' : ActorMethod<[GenreId], [] | [Genre]>,
  'getMyReadProgress' : ActorMethod<[ComicId], [] | [ReadProgress]>,
  'getMyResumeReading' : ActorMethod<[bigint], Array<[Comic, ReadProgress]>>,
  'getTrendingComics' : ActorMethod<[bigint], Array<TrendingEntry>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'incrementComicViews' : ActorMethod<[ComicId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChapters' : ActorMethod<[ComicId], Array<ChapterView>>,
  'listComics' : ActorMethod<[], Array<ComicView>>,
  'listGenres' : ActorMethod<[], Array<Genre>>,
  'registerUploadedImage' : ActorMethod<
    [ChapterId, ExternalBlob],
    UploadSession
  >,
  'rollbackUpload' : ActorMethod<[ChapterId], bigint>,
  'saveMyReadProgress' : ActorMethod<[SaveReadProgressRequest], undefined>,
  'searchComics' : ActorMethod<[string], Array<ComicView>>,
  'updateChapterDraft' : ActorMethod<
    [ChapterId, UpdateChapterDraftArgs],
    ChapterView
  >,
  'updateComic' : ActorMethod<[ComicId, UpdateComicArgs], ComicView>,
  'updateMyProfile' : ActorMethod<[UpdateProfileRequest], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];