/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const ComicId = IDL.Nat;
export const ChapterId = IDL.Nat;
export const ChapterInput = IDL.Record({
  'title' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'comicId' : ComicId,
  'images' : IDL.Vec(IDL.Text),
});
export const ComicInput = IDL.Record({
  'title' : IDL.Text,
  'isPremium' : IDL.Bool,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'ownerUploaded' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'genres' : IDL.Vec(IDL.Text),
  'coverUrl' : IDL.Text,
  'isPinned' : IDL.Bool,
  'isTrending' : IDL.Bool,
});
export const FAQInput = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
  'isUserQuestion' : IDL.Bool,
});
export const Timestamp = IDL.Int;
export const ChapterPublic = IDL.Record({
  'id' : ChapterId,
  'title' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'createdAt' : Timestamp,
  'comicId' : ComicId,
  'updatedAt' : Timestamp,
  'images' : IDL.Vec(IDL.Text),
});
export const ComicPublic = IDL.Record({
  'id' : ComicId,
  'title' : IDL.Text,
  'isPremium' : IDL.Bool,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'ownerUploaded' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'genres' : IDL.Vec(IDL.Text),
  'coverUrl' : IDL.Text,
  'likesCount' : IDL.Nat,
  'isPinned' : IDL.Bool,
  'isTrending' : IDL.Bool,
  'viewsCount' : IDL.Nat,
});
export const ReadingProgress = IDL.Record({
  'scrollPosition' : IDL.Nat,
  'chapterId' : ChapterId,
  'comicId' : ComicId,
  'lastReadAt' : Timestamp,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'chapterId' : IDL.Opt(ChapterId),
  'comicId' : ComicId,
});
export const FAQPublic = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'question' : IDL.Text,
  'createdAt' : IDL.Int,
  'answer' : IDL.Text,
  'approved' : IDL.Bool,
  'category' : IDL.Text,
  'isUserQuestion' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func(
      [UserId, ComicId, IDL.Opt(ChapterId), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'approveFAQ' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'bookmarkComic' : IDL.Func([ComicId], [IDL.Bool], []),
  'createChapter' : IDL.Func([ChapterInput], [ChapterId], []),
  'createComic' : IDL.Func([ComicInput], [ComicId], []),
  'createFAQ' : IDL.Func([FAQInput], [IDL.Nat], []),
  'deleteChapter' : IDL.Func([ChapterId], [IDL.Bool], []),
  'deleteComic' : IDL.Func([ComicId], [IDL.Bool], []),
  'deleteFAQ' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getChapter' : IDL.Func([ChapterId], [IDL.Opt(ChapterPublic)], ['query']),
  'getComic' : IDL.Func([ComicId], [IDL.Opt(ComicPublic)], ['query']),
  'getLikes' : IDL.Func([ComicId], [IDL.Opt(IDL.Nat)], ['query']),
  'getProgress' : IDL.Func(
      [UserId, ComicId],
      [IDL.Opt(ReadingProgress)],
      ['query'],
    ),
  'getTrending' : IDL.Func([IDL.Nat], [IDL.Vec(ComicPublic)], ['query']),
  'getViews' : IDL.Func([ComicId], [IDL.Opt(IDL.Nat)], ['query']),
  'likeComic' : IDL.Func([ComicId], [IDL.Bool], []),
  'listChapters' : IDL.Func([ComicId], [IDL.Vec(ChapterPublic)], ['query']),
  'listComics' : IDL.Func([], [IDL.Vec(ComicPublic)], ['query']),
  'listComments' : IDL.Func([ComicId], [IDL.Vec(Comment)], ['query']),
  'listFAQs' : IDL.Func([IDL.Bool], [IDL.Vec(FAQPublic)], ['query']),
  'listProgress' : IDL.Func([UserId], [IDL.Vec(ReadingProgress)], ['query']),
  'saveProgress' : IDL.Func([UserId, ReadingProgress], [], []),
  'submitFAQ' : IDL.Func([FAQInput], [IDL.Nat], []),
  'unbookmarkComic' : IDL.Func([ComicId], [IDL.Bool], []),
  'unlikeComic' : IDL.Func([ComicId], [IDL.Bool], []),
  'updateChapter' : IDL.Func([ChapterId, ChapterInput], [IDL.Bool], []),
  'updateComic' : IDL.Func([ComicId, ComicInput], [IDL.Bool], []),
  'updateFAQ' : IDL.Func([IDL.Nat, FAQInput], [IDL.Bool], []),
  'viewComic' : IDL.Func([ComicId], [IDL.Bool], []),
  'voteFAQ' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const ComicId = IDL.Nat;
  const ChapterId = IDL.Nat;
  const ChapterInput = IDL.Record({
    'title' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'comicId' : ComicId,
    'images' : IDL.Vec(IDL.Text),
  });
  const ComicInput = IDL.Record({
    'title' : IDL.Text,
    'isPremium' : IDL.Bool,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'ownerUploaded' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'genres' : IDL.Vec(IDL.Text),
    'coverUrl' : IDL.Text,
    'isPinned' : IDL.Bool,
    'isTrending' : IDL.Bool,
  });
  const FAQInput = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
    'isUserQuestion' : IDL.Bool,
  });
  const Timestamp = IDL.Int;
  const ChapterPublic = IDL.Record({
    'id' : ChapterId,
    'title' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'createdAt' : Timestamp,
    'comicId' : ComicId,
    'updatedAt' : Timestamp,
    'images' : IDL.Vec(IDL.Text),
  });
  const ComicPublic = IDL.Record({
    'id' : ComicId,
    'title' : IDL.Text,
    'isPremium' : IDL.Bool,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'ownerUploaded' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'genres' : IDL.Vec(IDL.Text),
    'coverUrl' : IDL.Text,
    'likesCount' : IDL.Nat,
    'isPinned' : IDL.Bool,
    'isTrending' : IDL.Bool,
    'viewsCount' : IDL.Nat,
  });
  const ReadingProgress = IDL.Record({
    'scrollPosition' : IDL.Nat,
    'chapterId' : ChapterId,
    'comicId' : ComicId,
    'lastReadAt' : Timestamp,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'chapterId' : IDL.Opt(ChapterId),
    'comicId' : ComicId,
  });
  const FAQPublic = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'question' : IDL.Text,
    'createdAt' : IDL.Int,
    'answer' : IDL.Text,
    'approved' : IDL.Bool,
    'category' : IDL.Text,
    'isUserQuestion' : IDL.Bool,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func(
        [UserId, ComicId, IDL.Opt(ChapterId), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveFAQ' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'bookmarkComic' : IDL.Func([ComicId], [IDL.Bool], []),
    'createChapter' : IDL.Func([ChapterInput], [ChapterId], []),
    'createComic' : IDL.Func([ComicInput], [ComicId], []),
    'createFAQ' : IDL.Func([FAQInput], [IDL.Nat], []),
    'deleteChapter' : IDL.Func([ChapterId], [IDL.Bool], []),
    'deleteComic' : IDL.Func([ComicId], [IDL.Bool], []),
    'deleteFAQ' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getChapter' : IDL.Func([ChapterId], [IDL.Opt(ChapterPublic)], ['query']),
    'getComic' : IDL.Func([ComicId], [IDL.Opt(ComicPublic)], ['query']),
    'getLikes' : IDL.Func([ComicId], [IDL.Opt(IDL.Nat)], ['query']),
    'getProgress' : IDL.Func(
        [UserId, ComicId],
        [IDL.Opt(ReadingProgress)],
        ['query'],
      ),
    'getTrending' : IDL.Func([IDL.Nat], [IDL.Vec(ComicPublic)], ['query']),
    'getViews' : IDL.Func([ComicId], [IDL.Opt(IDL.Nat)], ['query']),
    'likeComic' : IDL.Func([ComicId], [IDL.Bool], []),
    'listChapters' : IDL.Func([ComicId], [IDL.Vec(ChapterPublic)], ['query']),
    'listComics' : IDL.Func([], [IDL.Vec(ComicPublic)], ['query']),
    'listComments' : IDL.Func([ComicId], [IDL.Vec(Comment)], ['query']),
    'listFAQs' : IDL.Func([IDL.Bool], [IDL.Vec(FAQPublic)], ['query']),
    'listProgress' : IDL.Func([UserId], [IDL.Vec(ReadingProgress)], ['query']),
    'saveProgress' : IDL.Func([UserId, ReadingProgress], [], []),
    'submitFAQ' : IDL.Func([FAQInput], [IDL.Nat], []),
    'unbookmarkComic' : IDL.Func([ComicId], [IDL.Bool], []),
    'unlikeComic' : IDL.Func([ComicId], [IDL.Bool], []),
    'updateChapter' : IDL.Func([ChapterId, ChapterInput], [IDL.Bool], []),
    'updateComic' : IDL.Func([ComicId, ComicInput], [IDL.Bool], []),
    'updateFAQ' : IDL.Func([IDL.Nat, FAQInput], [IDL.Bool], []),
    'viewComic' : IDL.Func([ComicId], [IDL.Bool], []),
    'voteFAQ' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };