/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UpdateComicArgs {
    title: string;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
}
export interface UpdateChapterDraftArgs {
    title: string;
    number: number;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ProfileId = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Genre {
    id: GenreId;
    name: string;
    slug: string;
}
export type GenreId = string;
export interface ComicView {
    id: ComicId;
    title: string;
    updated_at: Timestamp;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
    created_at: Timestamp;
    author_id: UserId;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ChapterView {
    id: ChapterId;
    title: string;
    updated_at: Timestamp;
    created_at: Timestamp;
    comic_id: ComicId;
    is_published: boolean;
    number: number;
    image_blobs: Array<ExternalBlob>;
}
export type UserId = Principal;
export interface SaveReadProgressRequest {
    comic_id: ComicId;
    scroll_pixel_y: bigint;
    chapter_id: ChapterId;
}
export interface UpdateProfileRequest {
    bio?: string;
    profile_picture_url?: string;
    display_name?: string;
}
export type ComicId = string;
export interface TrendingEntry {
    views: bigint;
    last_updated: Timestamp;
    comic_id: ComicId;
    hot_score: number;
}
export interface UploadSession {
    status: UploadStatus;
    updated_at: Timestamp;
    chapter_id: ChapterId;
    uploaded_blobs: Array<ExternalBlob>;
    started_at: Timestamp;
}
export interface CreateComicArgs {
    title: string;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
}
export interface Comic {
    id: ComicId;
    title: string;
    updated_at: Timestamp;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
    created_at: Timestamp;
    author_id: UserId;
    is_deleted: boolean;
}
export type ChapterId = string;
export interface ReadProgress {
    user_id: ProfileId;
    comic_id: ComicId;
    scroll_pixel_y: bigint;
    chapter_id: ChapterId;
    last_read_at: Timestamp;
}
export interface UserProfile {
    id: ProfileId;
    bio: string;
    updated_at: Timestamp;
    created_at: Timestamp;
    profile_picture_url?: string;
    display_name: string;
    auth_id: string;
    handle: string;
    is_creator: boolean;
}
export interface CreateChapterArgs {
    title: string;
    comic_id: ComicId;
    number: number;
}
export enum UploadStatus {
    published = "published",
    uploading = "uploading",
    draft = "draft",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    beginUpload(chapter_id: ChapterId): Promise<UploadSession>;
    commitUpload(chapter_id: ChapterId): Promise<ChapterView>;
    createChapter(args: CreateChapterArgs): Promise<ChapterView>;
    createComic(args: CreateComicArgs): Promise<ComicView>;
    deleteChapter(id: ChapterId): Promise<void>;
    deleteComic(id: ComicId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getChapter(id: ChapterId): Promise<ChapterView | null>;
    getComic(id: ComicId): Promise<ComicView | null>;
    getComicsByGenre(genreId: GenreId): Promise<Array<ComicView>>;
    getGenre(id: GenreId): Promise<Genre | null>;
    getMyReadProgress(comicId: ComicId): Promise<ReadProgress | null>;
    getMyResumeReading(limit: bigint): Promise<Array<[Comic, ReadProgress]>>;
    getTrendingComics(limit: bigint): Promise<Array<TrendingEntry>>;
    getUserProfile(userId: string): Promise<UserProfile | null>;
    incrementComicViews(comicId: ComicId): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listChapters(comic_id: ComicId): Promise<Array<ChapterView>>;
    listComics(): Promise<Array<ComicView>>;
    listGenres(): Promise<Array<Genre>>;
    registerUploadedImage(chapter_id: ChapterId, blob: ExternalBlob): Promise<UploadSession>;
    rollbackUpload(chapter_id: ChapterId): Promise<bigint>;
    saveMyReadProgress(req: SaveReadProgressRequest): Promise<void>;
    searchComics(searchQuery: string): Promise<Array<ComicView>>;
    updateChapterDraft(id: ChapterId, args: UpdateChapterDraftArgs): Promise<ChapterView>;
    updateComic(id: ComicId, args: UpdateComicArgs): Promise<ComicView>;
    updateMyProfile(req: UpdateProfileRequest): Promise<UserProfile>;
}
import type { ChapterId as _ChapterId, ChapterView as _ChapterView, Comic as _Comic, ComicId as _ComicId, ComicView as _ComicView, CreateComicArgs as _CreateComicArgs, ExternalBlob as _ExternalBlob, Genre as _Genre, ProfileId as _ProfileId, ReadProgress as _ReadProgress, Timestamp as _Timestamp, UpdateComicArgs as _UpdateComicArgs, UpdateProfileRequest as _UpdateProfileRequest, UploadSession as _UploadSession, UploadStatus as _UploadStatus, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async beginUpload(arg0: ChapterId): Promise<UploadSession> {
        if (this.processError) {
            try {
                const result = await this.actor.beginUpload(arg0);
                return from_candid_UploadSession_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.beginUpload(arg0);
            return from_candid_UploadSession_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async commitUpload(arg0: ChapterId): Promise<ChapterView> {
        if (this.processError) {
            try {
                const result = await this.actor.commitUpload(arg0);
                return from_candid_ChapterView_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.commitUpload(arg0);
            return from_candid_ChapterView_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createChapter(arg0: CreateChapterArgs): Promise<ChapterView> {
        if (this.processError) {
            try {
                const result = await this.actor.createChapter(arg0);
                return from_candid_ChapterView_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChapter(arg0);
            return from_candid_ChapterView_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createComic(arg0: CreateComicArgs): Promise<ComicView> {
        if (this.processError) {
            try {
                const result = await this.actor.createComic(await to_candid_CreateComicArgs_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ComicView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComic(await to_candid_CreateComicArgs_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ComicView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteChapter(arg0: ChapterId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteComic(arg0: ComicId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComic(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapter(arg0: ChapterId): Promise<ChapterView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComic(arg0: ComicId): Promise<ComicView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComic(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComic(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComicsByGenre(arg0: GenreId): Promise<Array<ComicView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComicsByGenre(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComicsByGenre(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGenre(arg0: GenreId): Promise<Genre | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenre(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenre(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReadProgress(arg0: ComicId): Promise<ReadProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReadProgress(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReadProgress(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyResumeReading(arg0: bigint): Promise<Array<[Comic, ReadProgress]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyResumeReading(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyResumeReading(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingComics(arg0: bigint): Promise<Array<TrendingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingComics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingComics(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementComicViews(arg0: ComicId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementComicViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementComicViews(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChapters(arg0: ComicId): Promise<Array<ChapterView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChapters(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChapters(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listComics(): Promise<Array<ComicView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComics();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComics();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGenres(): Promise<Array<Genre>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGenres();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGenres();
            return result;
        }
    }
    async registerUploadedImage(arg0: ChapterId, arg1: ExternalBlob): Promise<UploadSession> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUploadedImage(arg0, await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UploadSession_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUploadedImage(arg0, await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UploadSession_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async rollbackUpload(arg0: ChapterId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.rollbackUpload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rollbackUpload(arg0);
            return result;
        }
    }
    async saveMyReadProgress(arg0: SaveReadProgressRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyReadProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyReadProgress(arg0);
            return result;
        }
    }
    async searchComics(arg0: string): Promise<Array<ComicView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchComics(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchComics(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateChapterDraft(arg0: ChapterId, arg1: UpdateChapterDraftArgs): Promise<ChapterView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapterDraft(arg0, arg1);
                return from_candid_ChapterView_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapterDraft(arg0, arg1);
            return from_candid_ChapterView_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateComic(arg0: ComicId, arg1: UpdateComicArgs): Promise<ComicView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComic(arg0, await to_candid_UpdateComicArgs_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ComicView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComic(arg0, await to_candid_UpdateComicArgs_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ComicView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: UpdateProfileRequest): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_UpdateProfileRequest_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_UpdateProfileRequest_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ChapterView_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChapterView): Promise<ChapterView> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ComicView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComicView): Promise<ComicView> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Comic_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comic): Promise<Comic> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_UploadSession_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadSession): Promise<UploadSession> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UploadStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadStatus): UploadStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChapterView]): Promise<ChapterView | null> {
    return value.length === 0 ? null : await from_candid_ChapterView_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ComicView]): Promise<ComicView | null> {
    return value.length === 0 ? null : await from_candid_ComicView_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Genre]): Genre | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReadProgress]): ReadProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UploadStatus;
    updated_at: _Timestamp;
    chapter_id: _ChapterId;
    uploaded_blobs: Array<_ExternalBlob>;
    started_at: _Timestamp;
}): Promise<{
    status: UploadStatus;
    updated_at: Timestamp;
    chapter_id: ChapterId;
    uploaded_blobs: Array<ExternalBlob>;
    started_at: Timestamp;
}> {
    return {
        status: from_candid_UploadStatus_n12(_uploadFile, _downloadFile, value.status),
        updated_at: value.updated_at,
        chapter_id: value.chapter_id,
        uploaded_blobs: await from_candid_vec_n14(_uploadFile, _downloadFile, value.uploaded_blobs),
        started_at: value.started_at
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChapterId;
    title: string;
    updated_at: _Timestamp;
    created_at: _Timestamp;
    comic_id: _ComicId;
    is_published: boolean;
    number: number;
    image_blobs: Array<_ExternalBlob>;
}): Promise<{
    id: ChapterId;
    title: string;
    updated_at: Timestamp;
    created_at: Timestamp;
    comic_id: ComicId;
    is_published: boolean;
    number: number;
    image_blobs: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        updated_at: value.updated_at,
        created_at: value.created_at,
        comic_id: value.comic_id,
        is_published: value.is_published,
        number: value.number,
        image_blobs: await from_candid_vec_n14(_uploadFile, _downloadFile, value.image_blobs)
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ComicId;
    title: string;
    updated_at: _Timestamp;
    cover_blob: _ExternalBlob;
    genre_ids: Array<string>;
    description: string;
    created_at: _Timestamp;
    author_id: _UserId;
}): Promise<{
    id: ComicId;
    title: string;
    updated_at: Timestamp;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
    created_at: Timestamp;
    author_id: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        updated_at: value.updated_at,
        cover_blob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.cover_blob),
        genre_ids: value.genre_ids,
        description: value.description,
        created_at: value.created_at,
        author_id: value.author_id
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ComicId;
    title: string;
    updated_at: _Timestamp;
    cover_blob: _ExternalBlob;
    genre_ids: Array<string>;
    description: string;
    created_at: _Timestamp;
    author_id: _UserId;
    is_deleted: boolean;
}): Promise<{
    id: ComicId;
    title: string;
    updated_at: Timestamp;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
    created_at: Timestamp;
    author_id: UserId;
    is_deleted: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        updated_at: value.updated_at,
        cover_blob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.cover_blob),
        genre_ids: value.genre_ids,
        description: value.description,
        created_at: value.created_at,
        author_id: value.author_id,
        is_deleted: value.is_deleted
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProfileId;
    bio: string;
    updated_at: _Timestamp;
    created_at: _Timestamp;
    profile_picture_url: [] | [string];
    display_name: string;
    auth_id: string;
    handle: string;
    is_creator: boolean;
}): {
    id: ProfileId;
    bio: string;
    updated_at: Timestamp;
    created_at: Timestamp;
    profile_picture_url?: string;
    display_name: string;
    auth_id: string;
    handle: string;
    is_creator: boolean;
} {
    return {
        id: value.id,
        bio: value.bio,
        updated_at: value.updated_at,
        created_at: value.created_at,
        profile_picture_url: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.profile_picture_url)),
        display_name: value.display_name,
        auth_id: value.auth_id,
        handle: value.handle,
        is_creator: value.is_creator
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Comic, _ReadProgress]): Promise<[Comic, ReadProgress]> {
    return [
        await from_candid_Comic_n32(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    uploading: null;
} | {
    draft: null;
} | {
    failed: null;
}): UploadStatus {
    return "published" in value ? UploadStatus.published : "uploading" in value ? UploadStatus.uploading : "draft" in value ? UploadStatus.draft : "failed" in value ? UploadStatus.failed : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComicView>): Promise<Array<ComicView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ComicView_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Comic, _ReadProgress]>): Promise<Array<[Comic, ReadProgress]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChapterView>): Promise<Array<ChapterView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ChapterView_n16(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateComicArgs_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateComicArgs): Promise<_CreateComicArgs> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UpdateComicArgs_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateComicArgs): Promise<_UpdateComicArgs> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    cover_blob: ExternalBlob;
    genre_ids: Array<string>;
    description: string;
}): Promise<{
    title: string;
    cover_blob: _ExternalBlob;
    genre_ids: Array<string>;
    description: string;
}> {
    return {
        title: value.title,
        cover_blob: await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.cover_blob),
        genre_ids: value.genre_ids,
        description: value.description
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    profile_picture_url?: string;
    display_name?: string;
}): {
    bio: [] | [string];
    profile_picture_url: [] | [string];
    display_name: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        profile_picture_url: value.profile_picture_url ? candid_some(value.profile_picture_url) : candid_none(),
        display_name: value.display_name ? candid_some(value.display_name) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
