/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export type Timestamp = bigint;
export interface FAQPublic {
    id: bigint;
    upvotes: bigint;
    question: string;
    createdAt: bigint;
    answer: string;
    approved: boolean;
    category: string;
    isUserQuestion: boolean;
}
export interface Comment {
    id: bigint;
    userId: UserId;
    createdAt: Timestamp;
    text: string;
    chapterId?: ChapterId;
    comicId: ComicId;
}
export interface ComicPublic {
    id: ComicId;
    title: string;
    isPremium: boolean;
    createdAt: Timestamp;
    description: string;
    author: string;
    ownerUploaded: boolean;
    isFeatured: boolean;
    genres: Array<string>;
    coverUrl: string;
    likesCount: bigint;
    isPinned: boolean;
    isTrending: boolean;
    viewsCount: bigint;
}
export interface ComicInput {
    title: string;
    isPremium: boolean;
    description: string;
    author: string;
    ownerUploaded: boolean;
    isFeatured: boolean;
    genres: Array<string>;
    coverUrl: string;
    isPinned: boolean;
    isTrending: boolean;
}
export type ComicId = bigint;
export interface ChapterPublic {
    id: ChapterId;
    title: string;
    chapterNumber: bigint;
    createdAt: Timestamp;
    comicId: ComicId;
    updatedAt: Timestamp;
    images: Array<string>;
}
export interface ChapterInput {
    title: string;
    chapterNumber: bigint;
    comicId: ComicId;
    images: Array<string>;
}
export interface ReadingProgress {
    scrollPosition: bigint;
    chapterId: ChapterId;
    comicId: ComicId;
    lastReadAt: Timestamp;
}
export interface FAQInput {
    question: string;
    answer: string;
    category: string;
    isUserQuestion: boolean;
}
export type ChapterId = bigint;
export interface backendInterface {
    addComment(userId: UserId, comicId: ComicId, chapterId: ChapterId | null, text: string): Promise<bigint>;
    approveFAQ(id: bigint): Promise<boolean>;
    bookmarkComic(_id: ComicId): Promise<boolean>;
    createChapter(input: ChapterInput): Promise<ChapterId>;
    createComic(input: ComicInput): Promise<ComicId>;
    createFAQ(input: FAQInput): Promise<bigint>;
    deleteChapter(id: ChapterId): Promise<boolean>;
    deleteComic(id: ComicId): Promise<boolean>;
    deleteFAQ(id: bigint): Promise<boolean>;
    getChapter(id: ChapterId): Promise<ChapterPublic | null>;
    getComic(id: ComicId): Promise<ComicPublic | null>;
    getLikes(id: ComicId): Promise<bigint | null>;
    getProgress(userId: UserId, comicId: ComicId): Promise<ReadingProgress | null>;
    getTrending(limit: bigint): Promise<Array<ComicPublic>>;
    getViews(id: ComicId): Promise<bigint | null>;
    likeComic(id: ComicId): Promise<boolean>;
    listChapters(comicId: ComicId): Promise<Array<ChapterPublic>>;
    listComics(): Promise<Array<ComicPublic>>;
    listComments(comicId: ComicId): Promise<Array<Comment>>;
    listFAQs(approvedOnly: boolean): Promise<Array<FAQPublic>>;
    listProgress(userId: UserId): Promise<Array<ReadingProgress>>;
    saveProgress(userId: UserId, progress: ReadingProgress): Promise<void>;
    submitFAQ(input: FAQInput): Promise<bigint>;
    unbookmarkComic(_id: ComicId): Promise<boolean>;
    unlikeComic(id: ComicId): Promise<boolean>;
    updateChapter(id: ChapterId, input: ChapterInput): Promise<boolean>;
    updateComic(id: ComicId, input: ComicInput): Promise<boolean>;
    updateFAQ(id: bigint, input: FAQInput): Promise<boolean>;
    viewComic(id: ComicId): Promise<boolean>;
    voteFAQ(id: bigint): Promise<boolean>;
}
import type { ChapterId as _ChapterId, ChapterPublic as _ChapterPublic, ComicId as _ComicId, ComicPublic as _ComicPublic, Comment as _Comment, ReadingProgress as _ReadingProgress, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: UserId, arg1: ComicId, arg2: ChapterId | null, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async approveFAQ(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveFAQ(arg0);
            return result;
        }
    }
    async bookmarkComic(arg0: ComicId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bookmarkComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookmarkComic(arg0);
            return result;
        }
    }
    async createChapter(arg0: ChapterInput): Promise<ChapterId> {
        if (this.processError) {
            try {
                const result = await this.actor.createChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChapter(arg0);
            return result;
        }
    }
    async createComic(arg0: ComicInput): Promise<ComicId> {
        if (this.processError) {
            try {
                const result = await this.actor.createComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComic(arg0);
            return result;
        }
    }
    async createFAQ(arg0: FAQInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFAQ(arg0);
            return result;
        }
    }
    async deleteChapter(arg0: ChapterId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteComic(arg0: ComicId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComic(arg0);
            return result;
        }
    }
    async deleteFAQ(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFAQ(arg0);
            return result;
        }
    }
    async getChapter(arg0: ChapterId): Promise<ChapterPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComic(arg0: ComicId): Promise<ComicPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComic(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComic(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikes(arg0: ComicId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikes(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikes(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(arg0: UserId, arg1: ComicId): Promise<ReadingProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrending(arg0: bigint): Promise<Array<ComicPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrending(arg0);
            return result;
        }
    }
    async getViews(arg0: ComicId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getViews(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViews(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async likeComic(arg0: ComicId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComic(arg0);
            return result;
        }
    }
    async listChapters(arg0: ComicId): Promise<Array<ChapterPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChapters(arg0);
            return result;
        }
    }
    async listComics(): Promise<Array<ComicPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComics();
            return result;
        }
    }
    async listComments(arg0: ComicId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFAQs(arg0: boolean): Promise<Array<FAQPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFAQs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFAQs(arg0);
            return result;
        }
    }
    async listProgress(arg0: UserId): Promise<Array<ReadingProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProgress(arg0);
            return result;
        }
    }
    async saveProgress(arg0: UserId, arg1: ReadingProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgress(arg0, arg1);
            return result;
        }
    }
    async submitFAQ(arg0: FAQInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFAQ(arg0);
            return result;
        }
    }
    async unbookmarkComic(arg0: ComicId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unbookmarkComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbookmarkComic(arg0);
            return result;
        }
    }
    async unlikeComic(arg0: ComicId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeComic(arg0);
            return result;
        }
    }
    async updateChapter(arg0: ChapterId, arg1: ChapterInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1);
            return result;
        }
    }
    async updateComic(arg0: ComicId, arg1: ComicInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComic(arg0, arg1);
            return result;
        }
    }
    async updateFAQ(arg0: bigint, arg1: FAQInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFAQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFAQ(arg0, arg1);
            return result;
        }
    }
    async viewComic(arg0: ComicId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.viewComic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewComic(arg0);
            return result;
        }
    }
    async voteFAQ(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.voteFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteFAQ(arg0);
            return result;
        }
    }
}
function from_candid_Comment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChapterPublic]): ChapterPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ComicPublic]): ComicPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReadingProgress]): ReadingProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChapterId]): ChapterId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    text: string;
    chapterId: [] | [_ChapterId];
    comicId: _ComicId;
}): {
    id: bigint;
    userId: UserId;
    createdAt: Timestamp;
    text: string;
    chapterId?: ChapterId;
    comicId: ComicId;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        text: value.text,
        chapterId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.chapterId)),
        comicId: value.comicId
    };
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n7(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterId | null): [] | [_ChapterId] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
